### ISSUE TITLE
QQ: is there logging?

### ISSUE THREAD

**Issue by mgaulton** [abrioy/rss_merge#1]
Anyway i can get it to dump why a fee wasn't found? I have one where the link works fine in the browser but your script won't retrieve and I can't tell why?

Love it, hope you keep working on it.

**Comment by mgaulton** [comment]
I dumped the returned data and got the below. Seems like it doesn't like something.
 Fetching feed "nzbsu".
X               > RSS feed not found: "https://url".
{'bozo': 1, 'href': 'https://url', 'encoding': 'us-ascii', 'status': 403, 'bozo_exception': SAXParseException('mismatched tag',), 'version': '', 'feed': {}, 'entries': [], 'headers': {'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'nginx', 'Connection': 'close', 'Transfer-Encoding': 'chunked', 'Date': 'Tue, 15 Sep 2015 17:28:44 GMT', 'Content-Type': 'text/html'}, 'namespaces': {}}

**Comment by abrioy** [comment]
I think you issues comes from an incorrect URL, could you give me the url of the feed you are trying to use ?

I'm in the process of adding real logging capabilities to the script, right now it just prints out a log on the standard output (if you launch the script from the command prompt it will print there).

**Comment by mgaulton** [comment]
Its not the url, i cut and paste into a browser, it works. Also, it's a personal url wiht apikey info in the url so I don't feel comfortable sharing it :(

**Comment by abrioy** [comment]
That's alright, what I see in the log you sent me is that feedparser, the library I use to parse the RSS feed, is returning an error. A 'mismatched tag' apparently, could you tell me if your feed can pass a validation without too much errors:
http://feedvalidator.org/

**Comment by mgaulton** [comment]
Funny, it doesn't pass the validator but works in other apps.

Its complaining about not being a full url but it looks full to me

<enclosure url="https://api.nzb.su/getnzb/772051e83f87ae540c214cc64fbbb137.nzb&amp;i=118675&amp;r=API" length="1977888311" type="application/x-nzb" />  <newznab:attr name="category" value="5000" />

line 27, column 1: url must be a full URL: https://api.nzb.su/getnzb/772051e83f87ae540c214cc64fbbb137.nzb&i=118675&r=API

**Comment by abrioy** [comment]
Most feeds don't pass the validation but will work anyway. The log you gave me earlier shows that feedparser can't parse your feed and I can't do anything about that.
You could try to run this code, it's basically what I use to parse the url, if the printed list is not empty my script should work:
`import feedparser;`
`feed = feedparser.parse(YOUR_URL);`
`print(feed.entries);`

**Comment by mgaulton** [comment]
Yea, i got an empty list. I'll bug those guys for violating the standard lol

**Comment by abrioy** [comment]
Sorry there is not much I can do short of writing a whole RSS parser, I could maybe whip out something dirty if it were a public feed. I'm still adding a proper logging system to the script tho.

**Comment by abrioy** [comment]
I just added command line arguments and a logger to the script. 
`-l` sets the logging level
`--log-output file` outputs the log to a file

**Comment by mgaulton** [comment]
Ok, i'im still stumped on that priv feed. Could I email you the link and output privately, maybe you can see what's going on?

**Comment by abrioy** [comment]
Sure, I don't think  Github does private messages anymore, just email it to me.

**Comment by abrioy** [comment]
I fixed it, the server was blocking my script because of the user agent used by feedparser. I should have seen it on log you first sent when you opened the issue because of the status code. Anyway, I want to thank you for your cooperation/patience and I hope you succeed in whatever you are hoping to do with this script, I you need any help or have any question please contact me.

**Comment by mgaulton** [comment]
nothing fancy, just trying to localize feeds so i can aggregate
locally and host off my inhouse apache. So far, the apps that are
consuming are ignoring the feeds, so i'm still trying to find out why.
uTorrent for example, seems to be iffy about consuming these so far
