### ISSUE TITLE
qq: is there a default timeout?

### ISSUE THREAD

**Issue by mgaulton** [abrioy/rss_merge#2]
I configured a feed and it just seemed to sit there forever, not sure saw anything timeout related.

**Comment by abrioy** [comment]
Issue discussed in https://github.com/Miow/RssMerge/issues/1

**Comment by mgaulton** [comment]
Hah, actually, this was for a different URL

**Comment by abrioy** [comment]
My bad, that I can fix, I added a timeout

**Comment by mgaulton** [comment]
No worry, thanks.
